-- Program
ALTER TABLE `Program` 
    ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
UPDATE `Program` SET `updatedAt` = NOW() WHERE `updatedAt` IS NULL;

-- Role
ALTER TABLE `Role` 
    ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
UPDATE `Role` SET `updatedAt` = NOW() WHERE `updatedAt` IS NULL;

-- User
ALTER TABLE `User` 
    ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
UPDATE `User` SET `updatedAt` = NOW() WHERE `updatedAt` IS NULL;

-- UserProgram
ALTER TABLE `UserProgram` 
    ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
UPDATE `UserProgram` SET `updatedAt` = NOW() WHERE `updatedAt` IS NULL;

-- UserRole
ALTER TABLE `UserRole` 
    ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
UPDATE `UserRole` SET `updatedAt` = NOW() WHERE `updatedAt` IS NULL;
